job section components, update flights
nadavl/loyalty-app pull request #5
Opened 2024-07-26 13:44 UTC by Andranik999

2024-07-29 10:24 UTC, nadavl requested changes
Great PR! see comments.

2024-07-29 10:24 UTC, nadavl commented on apps/expo/src/components/jobs-screen/apply-modal.tsx
> +
Better without space as it can be collapsed in IDE

2024-07-29 10:24 UTC, nadavl commented on apps/expo/src/components/jobs-screen/apply-modal.tsx
> +  const renderDashedLines = () => {
Should we memo this?

2024-07-29 10:24 UTC, nadavl commented on apps/expo/src/components/jobs-screen/apply-modal.tsx
> +  const onChange = (
Let's have a more meaningful name for this handler.

2024-07-29 10:24 UTC, nadavl commented on apps/expo/src/components/jobs-screen/apply-modal.tsx
> +              title={"I require relocation"}
Don't forget localization with i18n for all texts

2024-07-29 10:24 UTC, nadavl commented on apps/expo/src/components/jobs-screen/apply-modal.tsx
> +const styles = StyleSheet.create({
Are you going to separate styles to another file?

2024-07-29 10:24 UTC, nadavl commented on apps/expo/src/components/jobs-screen/job-item.tsx
> +
No need for extra line

2024-07-29 10:24 UTC, nadavl commented on apps/expo/src/components/jobs-screen/job-item.tsx
> +  const isWhite = index % 2 === 0;
Same As Above

2024-07-29 10:24 UTC, nadavl commented on apps/expo/src/components/jobs-screen/job-item.tsx
> +  function handleSelectItem() {
no need for a 1-line handlers

2024-07-29 10:24 UTC, nadavl commented on apps/expo/src/components/jobs-screen/job-item.tsx
> +const stylesFunction = (isApplied: boolean) =>
Move styles to separate file

2024-07-29 13:03 UTC, Andranik999 commented on apps/expo/src/app/(tabs)/_layout.tsx
> +            headerTitle: "Construction Job Board",
Yes, will change this with home screen addition, at first, there was no design for this

2024-07-29 13:08 UTC, Andranik999 commented on apps/expo/src/components/flights-screen/flight-item.tsx
> +  const isWhite = index % 2 === 0;
this is adding className not only color, that's why I used it like this

2024-07-29 13:10 UTC, Andranik999 commented on apps/expo/src/components/jobs-screen/apply-modal.tsx
> +const styles = StyleSheet.create({
Yes, wanted to add with home page, but will add here first

2024-07-29 13:17 UTC, Andranik999 commented on apps/expo/src/components/jobs-screen/apply-modal.tsx
> +  const renderDashedLines = () => {
Will look if it affects performance

2024-08-01 09:17 UTC, nadavl commented on apps/expo/package.json
> +    "@react-native-community/datetimepicker": "^8.2.0",
If that's the recommended one, that's OK 👍

2024-08-01 09:22 UTC, nadavl commented on apps/expo/src/components/flights-screen/flight-item.styles.ts
> +    color: CustomColors.textColorBold,
Maybe we can get this typography style as a Theme param?
i.e. "heading 1", "heading 2", "label", "text-medium" to include the relevant styles?

2024-08-01 09:22 UTC, nadavl commented on apps/expo/src/components/flights-screen/flight-item.styles.ts
> +    color: CustomColors.textColorBold,
Including font-size

2024-08-01 09:23 UTC, nadavl commented on apps/expo/src/components/flights-screen/flight-item.tsx
> +  const isWhite = index % 2 === 0;
OK, not a big deal.

2024-08-01 09:23 UTC, nadavl commented on apps/expo/src/components/jobs-screen/job-item.tsx
> +
⬆️

2024-08-02 05:59 UTC, nadavl approved these changes
Approving, although I see some points like i18n which should be addressed in another PR.

2024-08-02 09:46 UTC, merged